name: Build and Deploy Maven Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Handle SSH Key
        id: ssh-key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Upload .jar to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
        run: |
          scp -i private_key -o StrictHostKeyChecking=no target/*.jar $SERVER_USER@$SERVER_HOST:$SERVER_PATH
        continue-on-error: false

      - name: Stop existing Java process
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
          if pgrep -f 'java -jar $SERVER_PATH/test-ci-cd.jar'; then
            pkill -f 'java -jar $SERVER_PATH/test-ci-cd.jar';
          else
            echo 'No process found';
          fi"
        continue-on-error: true

      - name: Start new Java process
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "nohup java -jar $SERVER_PATH/test-ci-cd.jar > /dev/null 2>&1 &"
        continue-on-error: false

      - name: Cleanup
        if: always()
        run: rm private_key

      - name: Debug Environment Variables
        run: |
          echo "SERVER_USER: $SERVER_USER"
          echo "SERVER_HOST: $SERVER_HOST"
          echo "SERVER_PATH: $SERVER_PATH"
